import type { Order } from "@/types";
import { MOCK_PRODUCT_DETAIL } from "../products/mockProductDetails";

export const MOCK_ORDERS: Order[] = [
  {
    id: "VD-2025-001",
    placedAt: "12 Jun 2025, 10:30 AM",
    status: "delivered",
    total: "₹18,753",
    paymentMethod: "UPI · Google Pay",
    estimatedDelivery: "Delivered on 14 Jun 2025",
    deliveryAddress: {
      name: "Sandeep K A",
      line1: "Flat 4B, Green Valley Apartments",
      line2: "Near Lulu Mall",
      city: "Kochi",
      state: "Kerala",
      pincode: "682021",
    },
    items: [
      {
        product: MOCK_PRODUCT_DETAIL["1"],
        selectedVariants: { "ram-storage": "8-256", color: "black" },
        quantity: 1,
        price: "₹18,404",
      },
    ],
    tracking: [
      {
        status: "pending",
        label: "Order placed",
        timestamp: "12 Jun · 10:30 AM",
        completed: true,
        current: false,
      },
      {
        status: "confirmed",
        label: "Order confirmed",
        timestamp: "12 Jun · 11:00 AM",
        completed: true,
        current: false,
      },
      {
        status: "shipped",
        label: "Shipped",
        timestamp: "13 Jun · 2:00 PM · Delhivery #DL789456",
        completed: true,
        current: false,
      },
      {
        status: "out_for_delivery",
        label: "Out for delivery",
        timestamp: "14 Jun · 8:00 AM",
        completed: true,
        current: false,
      },
      {
        status: "delivered",
        label: "Delivered",
        timestamp: "14 Jun · 4:30 PM",
        completed: true,
        current: true,
      },
    ],
  },
  {
    id: "VD-2025-002",
    placedAt: "18 Jun 2025, 3:15 PM",
    status: "out_for_delivery",
    total: "₹1,548",
    paymentMethod: "Credit Card · HDFC",
    estimatedDelivery: "Expected by 6:00 PM today",
    deliveryAddress: {
      name: "Sandeep K A",
      line1: "Flat 4B, Green Valley Apartments",
      line2: "Near Lulu Mall",
      city: "Kochi",
      state: "Kerala",
      pincode: "682021",
    },
    items: [
      {
        product: MOCK_PRODUCT_DETAIL["11"],
        selectedVariants: { format: "paperback" },
        quantity: 2,
        price: "₹349",
      },
      {
        product: MOCK_PRODUCT_DETAIL["7"],
        selectedVariants: { size: "m", color: "pink" },
        quantity: 1,
        price: "₹1,199",
      },
    ],
    tracking: [
      {
        status: "pending",
        label: "Order placed",
        timestamp: "18 Jun · 3:15 PM",
        completed: true,
        current: false,
      },
      {
        status: "confirmed",
        label: "Order confirmed",
        timestamp: "18 Jun · 3:45 PM",
        completed: true,
        current: false,
      },
      {
        status: "shipped",
        label: "Shipped",
        timestamp: "19 Jun · 9:00 AM · BlueDart #BD456123",
        completed: true,
        current: false,
      },
      {
        status: "out_for_delivery",
        label: "Out for delivery",
        timestamp: "20 Jun · 8:30 AM",
        completed: true,
        current: true,
      },
      {
        status: "delivered",
        label: "Delivered",
        timestamp: "Expected by 6:00 PM",
        completed: false,
        current: false,
      },
    ],
  },
  {
    id: "VD-2025-003",
    placedAt: "20 Jun 2025, 9:00 AM",
    status: "confirmed",
    total: "₹38,490",
    paymentMethod: "UPI · PhonePe",
    estimatedDelivery: "Expected by 23 Jun 2025",
    deliveryAddress: {
      name: "Sandeep K A",
      line1: "Flat 4B, Green Valley Apartments",
      city: "Kochi",
      state: "Kerala",
      pincode: "682021",
    },
    items: [
      {
        product: MOCK_PRODUCT_DETAIL["1"],
        selectedVariants: { "ram-storage": "6-128", color: "blue" },
        quantity: 1,
        price: "₹15,999",
      },
    ],
    tracking: [
      {
        status: "pending",
        label: "Order placed",
        timestamp: "20 Jun · 9:00 AM",
        completed: true,
        current: false,
      },
      {
        status: "confirmed",
        label: "Order confirmed",
        timestamp: "20 Jun · 9:30 AM",
        completed: true,
        current: true,
      },
      {
        status: "shipped",
        label: "Shipped",
        timestamp: "Pending",
        completed: false,
        current: false,
      },
      {
        status: "out_for_delivery",
        label: "Out for delivery",
        timestamp: "Pending",
        completed: false,
        current: false,
      },
      {
        status: "delivered",
        label: "Delivered",
        timestamp: "Expected 23 Jun",
        completed: false,
        current: false,
      },
    ],
  },
  {
    id: "VD-2025-004",
    placedAt: "5 Jun 2025, 2:00 PM",
    status: "cancelled",
    total: "₹2,799",
    paymentMethod: "COD",
    deliveryAddress: {
      name: "Sandeep K A",
      line1: "Flat 4B, Green Valley Apartments",
      city: "Kochi",
      state: "Kerala",
      pincode: "682021",
    },
    items: [
      {
        product: MOCK_PRODUCT_DETAIL["1"],
        selectedVariants: {},
        quantity: 1,
        price: "₹2,799",
      },
    ],
    tracking: [
      {
        status: "pending",
        label: "Order placed",
        timestamp: "5 Jun · 2:00 PM",
        completed: true,
        current: false,
      },
      {
        status: "cancelled",
        label: "Order cancelled",
        timestamp: "5 Jun · 4:00 PM",
        completed: true,
        current: true,
      },
    ],
  },
];
